---
abstract: 'Manage Postgresql blobs from any DBI (dbh) capable object.'
author:
  - 'Jerome Eteve <jerome.eteve@gmail.com>'
build_requires:
  DBI: 0
  Moose: 0
  Test::Exception: 0.31
  Test::More: 0.98
  Test::postgresql: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pg-Blobs
requires:
  Moose::Role: 2.0401
version: 0.002
